plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url = "https://masa.dy.fi/maven/sakura-ryoko"
		content { includeGroupAndSubgroups("fi.dy.masa") }
	}
	// Litematica depends on conditional-mixin, which lives here.
	maven {
		url = 'https://maven.fallenbreath.me/releases'
		content { includeGroupAndSubgroups("me.fallenbreath") }
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	// Litematica and MaLiLib are built against Mojang's official mappings, so we must match them.
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	implementation "com.google.code.findbugs:jsr305:3.0.2"

	modImplementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"
	modImplementation "fi.dy.masa.litematica:litematica-fabric-${project.minecraft_version}:${project.litematica_version}"
}

processResources {
	def props = [
			version      : project.version,
			mod_id       : project.mod_id,
			minecraft    : project.minecraft_version,
			loader       : project.fabric_loader_version
	]
	inputs.properties props

	filesMatching("fabric.mod.json") {
		expand props
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}" }
	}
}
